export const ROOM_ROLE = {
	ADMIN: 'ADMIN',
	MODERATOR: 'MODERATOR',
	PRESENTER: 'PRESENTER',
	CUSTOMER: 'CUSTOMER',
	TEACHER: 'TEACHER',
	STUDENT: 'STUDENT',
};

export const ACTION_TYPE = {
	OPEN_CLASS: 'OPEN_CLASS',
	JOIN_CLASS: 'JOIN_CLASS',
};