export const ROOM_ROLE = {
	ADMIN: 'ADMIN',
	MODERATOR: 'MODERATOR',
	PRESENTER: 'PRESENTER',
	CUSTOMER: 'CUSTOMER',
	TEACHER: 'TEACHER',
	STUDENT: 'STUDENT',
};

export const ACTION_TYPE = {
	OPEN_CLASS: 'OPEN_CLASS',
	JOIN_CLASS: 'JOIN_CLASS',
	INIT_BIG_BOARD: 'INIT_BIG_BOARD',
	INIT_MY_STREAM: 'INIT_MY_STREAM',
	INIT_SMALL_BOARD: 'INIT_SMALL_BOARD',
};
